/* DO NOT EDIT THIS FILE - it is machine generated */
#include </root/jdk1.8.0_171/include/jni.h>
/* Header for class com_okcoin_vault_jni_CZcashj */

#ifndef _Included_com_okcoin_vault_jni_CZcashj
#define _Included_com_okcoin_vault_jni_CZcashj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_okcoin_vault_jni_CZcashj
 * Method:    getAddress
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_okcoin_vault_jni_CZcashj_getAddress
  (JNIEnv *env, jobject ob, jstring privKey);

/*
 * Class:     com_okcoin_vault_jni_CZcashj
 * Method:    produceUnsignedTx
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_okcoin_vault_jni_CZcashj_produceUnsignedTx
  (JNIEnv *env, jobject ob, jstring addr, jstring amount);

/*
 * Class:     com_okcoin_vault_jni_CZcashj
 * Method:    signTransaction
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_okcoin_vault_jni_CZcashj_signTransaction
  (JNIEnv *env, jobject ob, jbyteArray transacHex);

#ifdef __cplusplus
}
#endif
#endif
